---
output:
  pdf_document: default
  html_document: default
---
# Principes généraux de SHIBA
SHIBA est une application créée par le Groupe Méthodes en Recherche Clinique (GMRC) des hôpitaux universitaires de Strasbourg et les membres de l’équipe IMAGES – RaDoScauba du laboratoire iCUBE (CNRS UMR 7357). Elle est entièrement gratuite, sous licence CC-by-nc 4.0. 


SHIBA est une interface graphique permettant de réaliser des analyses bayésiennes via le logiciel de statistiques R et les packages de statistiques bayésiennes associés sans avoir à coder les instructions nécessaires pour obtenir ces analyses. Tout fonctionne par des glisser-déposer ou en cliquant sur les éléments dont vous avez besoin. 


L'utilisation de SHIBA implique cependant de connaître un minimum de notions sur les probabilités et sur ce que sont les méthodes bayésiennes. La présente page d’aide est là pour vous apporter les connaissances nécessaires pour utiliser correctement l'outil. 

**Cet outil est proposé sans aucune garantie de validité sur les résultats**.
**Si vous utilisez cet outil pour traiter des données médicales et a fortiori relevant de la recherche médicale, vous devez le faire dans le respect de la réglementation en vigueur. Les concepteurs de cet outil ne sont pas responsables de ce que vous en faites.**  

--- 

**Citation**

L'équipe vous remercie de bien vouloir la citer dans votre bibliographie lorsque vous aurez utilisé SHIBA pour vos travaux scientifiques. La référence est la suivante : Fabacher et toute sa bande de potes, SHIBA, un logiciel qui a du chien. _Journal de statistique canine bayésienne_. 2023;1(1):1-200.

--- 

Cet outil est mis à votre disposition sous licence CC BY-NC 4.0, c'est-à-dire : Pas d’Utilisation Commerciale 4.0 International. 


**Vous êtes autorisé à** :

- Partager — copier, distribuer et communiquer le matériel par tous moyens et sous tous formats
- Adapter — remixer, transformer et créer à partir du matériel
- L'Offrant ne peut retirer les autorisations concédées par la licence tant que vous appliquez les termes de cette licence.


**selon les conditions suivantes** :

- Attribution — Vous devez créditer l'Œuvre, intégrer un lien vers la licence et indiquer si des modifications ont été effectuées à l'Œuvre Vous devez indiquer ces informations par tous les moyens raisonnables, sans toutefois suggérer que l'Offrant vous soutient ou soutient la façon dont vous avez utilisé son Oeuvre.

- Pas d’Utilisation Commerciale — Vous n'êtes pas autorisé à faire un usage commercial de cette Œuvre, tout ou partie du matériel la composant.

- Pas de restrictions complémentaires — Vous n'êtes pas autorisé à appliquer des conditions légales ou des mesures techniques qui restreindraient légalement autrui à utiliser l'Œuvre dans les conditions décrites par la licence.




