# Fonctionnement général de SHIBA
SHIBA dispose de plusieurs onglets. Le premier onglet est consacré à l’importation et à la lecture de la base de données. Une base de données saisie dans un tableau sous la forme d’un tableur avec comme extension : .xlsx, .ods,  .txt ou .csv) devra être chargée à l’aide de ce premier onglet. Une fois la base de données ouverte dans SHIBA, vous pourrez choisir l’onglet correspondant aux analyses à réaliser. 

## Vocabulaire de base

La réalisation d’analyse statistique dans SHIBA suppose de connaître quelques éléments de vocabulaire statistique. 

-	**Paramètre** : tout ce qui peut quantifier un effet et que l’on peut exprimer sous forme numérique : une proportion, une moyenne, un taux d’incidence, une différence de proportions ou de moyennes, un coefficient de corrélation, un odds ratio (OR), un risque relatif (RR), la pente d’une droite de régression, etc. 
-	**Population** : une population est un ensemble exhaustif d’individus statistiques sur lequel on souhaite estimer la valeur d’un paramètre. En pratique, on ne connait jamais la valeur exacte de ce paramètre dans la population car celle-ci n’est pas connue dans sa totalité. La valeur du paramètre dans la population peut seulement être estimée via une méthode d’inférence à partir d’un échantillon. SHIBA utilise exclusivement de l’inférence bayésienne. Le paramètre dans la population est estimé à partir des données observées au cours d’une expérimentation et de la connaissance que vous aviez, avant de mener l’expérimentation, sur les valeurs de ce paramètre. CEtte connaissance peut être très vague ou très précise. Dans SHIBA, la valeur du paramètre dans la population est exprimée par une estimation ponctuelle de la valeur du paramètre assortie d’un intervalle de valeurs donnant la valeur du paramètre avec une certaine incertitude. On peut lui adjoindre la probabilité que le paramètre soit dans un intervalle donné, pré-spécifié, ou au-dessus d’une valeur seuil.
-	**Echantillon** : un échantillon est un ensemble de sujets extraits de la population étudiée, sur lequel on relève des données et que l’on utilise pour estimer la valeur du paramètre d’intérêt dans la population. 
-	**Données** : on appelle donnée toute mesure réalisée et observée sur un échantillon au cours d’une expérimentation. La donnée peut être qualitative ou quantitative. 

## Les différents types de variables

SHIBA peut traiter la totalité des types de variables statistiques. 
On trouve donc des méthodes pour traiter une : 

- **variable qualitative** 
- **variable quantitative**
  - variable quantitative discrète.
  - variable quantitative continue
    - variable quantitative continue bornée
      - d'un côté (en général par une valeur minimale, souvent nulle)
      - des deux côtés
  - score bornés, discret ou continu
- etc

A FINIR. 





