---
repo-actions: true
---

# Inférence univariée

L’onglet « Inférence univariée » contient deux sous-onglets. Le premier est consacré à l’estimation d’une moyenne et le second à l’estimation d’une proportion. Cette estimation se fait avec des méthodes bayésiennes. Il vous faudra donc spécifier à chaque fois une loi a priori pour le paramètre d’intérêt : une moyenne ou une proportion. 

## **Pour l’estimation d’une moyenne :** 
L’estimation bayésienne de la moyenne $\mu$ d’une variable quantitative se fait avec le modèle suivant : 

-	 La moyenne $\mu$ de la distribution est distribuée suivant une loi normale de moyenne $\mu$ et d’écart-type $\sigma$

-	 L’écart-type de la distribution suit une loi $\gamma(\alpha,\beta)$

Il faut donc exprimer la loi a priori sur chacun de ces deux paramètres pour obtenir l’estimation a posteriori de la moyenne de la distribution. 

Une boite à menu déroulant « Variable » vous permet de choisir la variable dont vous voulez estimer la moyenne. Le choix une fois réalisé, SHIBA va proposer automatiquement une loi a priori pour la moyenne de la variable sélectionnée. Cette loi a elle-même une moyenne (noté « a priori mu ») et un écart-type (noté « a priori sd ») mais il est possible de modifier leur valeur en utilisant les flèches des boites correspondantes ou en tapant directement une valeur. Vous verrez que les choix par défaut ne sont pas forcément pertinents notamment parce qu’ils peuvent englober des valeurs négatives souvent impossibles pour des paramètres biologiques. Il faut alors modifier la loi a priori pour qu’elle exprime votre connaissance a priori sur la valeur de la moyenne. La courbe située au-dessus des deux boites de dialogues permet une visualisation immédiate de la loi a priori spécifiée par les deux paramètres. Le paramètre d’écart-type permet de donner une plus ou moins grande précision sur la position de la moyenne. 


Dans le cas d’une moyenne, il faut également spécifier une loi a priori sur l’écart-type de la variable. La loi a priori est une loi gamma, ayant deux paramètres, alpha et beta. Le paramètre alpha est un paramètre de position et le paramètre Beta est un paramètre de précision. 

Un bouton « Définition seuil / Two-It » ouvre un menu pop-up permettant de spécifier un seuil à tester ainsi que les bornes des deux intervalles H<sub>A</sub> et H<sub>P</sub>.

En appuyant sur le bouton « Go » vous obtiendrez les résultats des analyses dans la partie droite de l’écran.

SHIBA fournit un rappel des paramètres utilisés dans la loi a priori, puis un descriptif de la connaissance a priori sur la moyenne et l’écart-type exprimée par ces deux lois a priori. Il fournit ensuite l’estimation a posteriori de la moyenne et de l’écart-type de la distribution. 






## **Pour l’estimation d’une proportion :** 

L’estimation bayésienne d’une proportion $\pi$ ou taux de succès d’une variable binaire, se fait avec le modèle suivant : 
-	Le taux de succès $\pi$ est distribué suivant une loi $Beta(\alpha,\beta)$

Il faut donc exprimer la loi a priori de $\pi$ en spécifiant la valeur de $\alpha$ et de $\beta$. Ces deux paramètres peuvent s’interpréter respectivement comme un nombre de succès ($\alpha$) et un nombre d’échecs ($\beta$) sur N essais.

Une boite à menu déroulant « Variable » vous permet de choisir la variable dont vous voulez estimer le taux de succès. Par défaut, SHIBA propose une loi Beta de Jeffreys Beta(0,5, 0,5) mais il est possible de modifier la valeur des deux paramètres en utilisant les flèches des boites correspondantes ou en tapant directement une valeur. La courbe située au-dessus des deux boites de dialogues permet une visualisation immédiate de la loi a priori spécifiée par les deux paramètres. 

Un bouton « Définition seuil / Two-It » ouvre un menu pop-up permettant de spécifier un seuil à tester ainsi que les bornes des deux intervalles H<sub>A</sub> et H<sub>P</sub>.

En appuyant sur le bouton « Go » vous obtiendrez les résultats des analyses dans la partie droite de l’écran.

SHIBA fournit un rappel des paramètres utilisés dans la loi a priori, puis un descriptif de la connaissance a priori sur la proportion exprimée par cette loi a priori. Il fournit ensuite l’estimation a posteriori de la proportion. 

Un graphique combinant la loi a priori et la loi a posteriori est automatiquement fournit. Lorsqu’un seuil et/ou qu’un 2IT est spécifié, le graphique contient une visualisation de chaque intervalle. Les probabilités associées sont données dans le tableau de résultats. 


